alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

domains:
  - domain: api.chatmiimii.com
    type: PRIMARY
    zone: chatmiimii.com

# Environment variables should be set in the DigitalOcean App Platform UI
# Do NOT use template syntax like ${VARIABLE_NAME} - use actual values
envs: []

features:
  - buildpack-stack=ubuntu-22

ingress:
  rules:
    - component:
        name: miimii
      match:
        authority:
          exact: ""
        path:
          prefix: /

name: miimii-app
region: fra

services:
  - name: miimii
    dockerfile_path: /Dockerfile
    source_dir: /
    http_port: 3000
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-0.5gb

    github:
      branch: main
      deploy_on_push: true
      repo: DesignerDev23/MiiMii

    # IMPORTANT: Set these environment variables in the DigitalOcean App Platform UI
    # Go to: App Settings > Environment Variables > Add Variable
    # DO NOT use ${VARIABLE_NAME} syntax - set actual values in the UI
    envs:
      # Basic Configuration (REQUIRED)
      - key: PORT
        scope: RUN_AND_BUILD_TIME
        value: "3000"
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: BASE_URL
        scope: RUN_AND_BUILD_TIME
        value: https://api.chatmiimii.com

      # Database Configuration (REQUIRED - Set ONE of these options)
      # Option 1: Full connection URL (RECOMMENDED)
      - key: DB_CONNECTION_URL
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      
      # Option 2: Individual database parameters (alternative to DB_CONNECTION_URL)
      - key: DB_HOST
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: DB_PORT
        scope: RUN_AND_BUILD_TIME
        value: "5432"
      - key: DB_NAME
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: DB_USER
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: DB_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"

      # JWT Configuration (REQUIRED)
      - key: APP_SECRET
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: JWT_EXPIRES_IN
        scope: RUN_AND_BUILD_TIME
        value: "30d"

      # WhatsApp Configuration (REQUIRED for WhatsApp features)
      - key: BOT_ACCESS_TOKEN
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: BOT_PHONE_NUMBER_ID
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: BOT_BUSINESS_ACCOUNT_ID
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: BOT_WEBHOOK_VERIFY_TOKEN
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"

      # Banking Configuration (REQUIRED for banking features)
      - key: BANK_CONSUMER_KEY
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: BANK_CONSUMER_SECRET
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"

      # Provider Configuration (REQUIRED for some features)
      - key: PROVIDER_USERNAME
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: PROVIDER_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: BILAL_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"

      # KYC Configuration (REQUIRED for KYC features)
      - key: DOJAH_APP_ID
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: DOJAH_SECRET_KEY
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: DOJAH_PUBLIC_KEY
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"

      # AI Configuration (REQUIRED for AI features)
      - key: AI_API_KEY
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: AI_MODEL
        scope: RUN_AND_BUILD_TIME
        value: "gpt-4-turbo"

      # Optional Configuration
      - key: REDIS_URL
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI_OR_LEAVE_EMPTY"
      - key: GOOGLE_APPLICATION_CREDENTIALS
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI_OR_LEAVE_EMPTY"
      - key: MAX_FILE_SIZE
        scope: RUN_AND_BUILD_TIME
        value: "10485760"
      - key: UPLOAD_PATH
        scope: RUN_AND_BUILD_TIME
        value: "uploads/"
      - key: WEBHOOK_SECRET
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"
      - key: ADMIN_EMAIL
        scope: RUN_AND_BUILD_TIME
        value: "admin@miimii.com"
      - key: ADMIN_PASSWORD
        scope: RUN_AND_BUILD_TIME
        value: "SET_THIS_IN_DO_UI"

      # Fee Configuration (with defaults)
      - key: TRANSFER_FEE_PERCENTAGE
        scope: RUN_AND_BUILD_TIME
        value: "0.5"
      - key: PLATFORM_FEE
        scope: RUN_AND_BUILD_TIME
        value: "5"
      - key: BELLBANK_FEE
        scope: RUN_AND_BUILD_TIME
        value: "20"
      - key: MAINTENANCE_FEE
        scope: RUN_AND_BUILD_TIME
        value: "100"
      - key: DATA_PURCHASE_FEE
        scope: RUN_AND_BUILD_TIME
        value: "10"

      # Rate Limiting Configuration (with defaults)
      - key: RATE_LIMIT_WINDOW_MS
        scope: RUN_AND_BUILD_TIME
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        scope: RUN_AND_BUILD_TIME
        value: "100"

      # Logging Configuration
      - key: LOG_LEVEL
        scope: RUN_AND_BUILD_TIME
        value: "info"
